### PR TITLE
making switch branch work with ajax

### PR DESCRIPTION
**Pull request by kdorer**

### CODE REVIEW

**Comment by bammons** [comment]
I wanna get alan's in first and then have you merge his.

**Comment by Onattigorn** [comment]
bailey wants me to get it in teehee

**Comment by bammons** [comment]
I'll be at school at 11 if you wanna meet up

**Comment by bammons** [comment]
+1

**Comment by Linkster700** [comment]
+1

**Comment by ChristianMurphy** [comment]
+1

**Pull request merged**
