### PR TITLE
Issue-91.1

### PR DESCRIPTION
**Pull request by tcavaletto**

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
[-1 there is no point to these commits](https://global3.memecdn.com/changes_o_724155.jpg)

**Comment by bammons** [comment]
There is. He made the test cases use multiple FactoryGirl objects and tested against multiple users. I'm going to +1

**Comment by bammons** [comment]
Two users are made. Line 31 and line 33. User signs in and searches ta. User then selects follow button for the second created user "user_follow". Notification pops up saying now following Taylor Cavaletto. 2 users. user follows user_follow.

**Comment by kdorer** [comment]
+1

**Pull request merged**
