### PR TITLE
Issue 91

### PR DESCRIPTION
**Pull request by tcavaletto**
Unit tests to up coverage on search controller

### CODE REVIEW

**Comment by bammons** [comment]
<a href="http://25.media.tumblr.com/tumblr_lyr8i5dY1N1r71s6to1_250.jpg">+1</a> it's nice to see some more tests being written. I'm currently working on upping coverage for the curriculum controller.

**Comment by bammons** [comment]
still +1

**Comment by kdorer** [comment]
+1

**Comment by Onattigorn** [comment]
+1 Looks good

**Pull request merged**
