### PR TITLE
Adding documentation coverage badge

### PR DESCRIPTION
**Pull request by ChristianMurphy**

### CODE REVIEW

**Comment by Onattigorn** [comment]
yea coverage dropped by 9/11 this is great news

**Comment by bammons** [comment]
Can you lock in the versions for rspec/capybara back to a state where they were working and update the pr?

**Comment by ChristianMurphy** [comment]
sure, where would I find which version was used before the PR?

**Comment by bammons** [comment]
Just go to last build and check the version it built with

**Comment by ChristianMurphy** [comment]
So I froze rspec-rails and capybara at pre-failure versions, and the tests are still failing... :confused: :question:

**Comment by bammons** [comment]
Just locking in the version won't do, you have to lock it in to the last working state as well. All you had to do was look at the last green build and lock in capybara and rspec to the versions installed there.

rspec-rails (2.14.2)
capybara (2.2.1)

**Comment by ChristianMurphy** [comment]
So is this good to go?

**Pull request closed without merging**
