### PR TITLE
Task 886

### PR DESCRIPTION
**Pull request by tcavaletto**
Added dummy layouts for friends and curricula lists on public and personal profiles that can be changed to be dynamic once friends/curricula functionality is built.

### CODE REVIEW

**Comment by bammons** [comment]
<a href="http://i1.kym-cdn.com/entries/icons/original/000/013/075/majesticlineman.jpg">+1</a>

**Comment by Linkster700** [comment]
+1

**Comment by kdorer** [comment]
+1

**Comment by Onattigorn** [comment]
+1 Because Rift

**Pull request merged**
