### PR TITLE
it works

### PR DESCRIPTION
**Pull request by ChristianMurphy**
#142

### CODE REVIEW

**Comment by bammons** [comment]
I won't merge this without seeing it first. Also, it may work for now because you aren't pulling back any contributed curriculum.

**Comment by bammons** [comment]
And you need to remove the better_errors gem. Wait to do that until after you have show me the controller working completely

**Comment by ChristianMurphy** [comment]
viola

**Comment by ChristianMurphy** [comment]
this code is not more unverifiable than the code it is simplifying.
would you prefer I go back and blame the original merge that brought this in?

**Comment by ChristianMurphy** [comment]
and ruby arrays can hold and manipulate multiple types of objects
http://zetcode.com/lang/rubytutorial/arrays/

**Pull request closed without merging**
